example/example/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('pyfb_rating.urls', namespace='pyfb-rating')),
]

pyfb_rating/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, include
from rest_framework import routers

from . import api
from . import views


app_name = 'pyfb_rating'

router = routers.DefaultRouter()
router.register(r'customerrcallocation', api.CustomerRcAllocationViewSet)
router.register(r'callernumlist', api.CallerNumListViewSet)
router.register(r'providerratecard', api.ProviderRatecardViewSet)
router.register(r'customerratecard', api.CustomerRatecardViewSet)
router.register(r'customerprefixrate', api.CustomerPrefixRateViewSet)
router.register(r'providerprefixrate', api.ProviderPrefixRateViewSet)
router.register(r'customerdestinationrate', api.CustomerDestinationRateViewSet)
router.register(r'providerdestinationrate', api.ProviderDestinationRateViewSet)
router.register(r'customercountrytyperate', api.CustomerCountryTypeRateViewSet)
router.register(r'providercountrytyperate', api.ProviderCountryTypeRateViewSet)
router.register(r'customercountryrate', api.CustomerCountryRateViewSet)
router.register(r'providercountryrate', api.ProviderCountryRateViewSet)
router.register(r'customerregiontyperate', api.CustomerRegionTypeRateViewSet)
router.register(r'providerregiontyperate', api.ProviderRegionTypeRateViewSet)
router.register(r'customerregionrate', api.CustomerRegionRateViewSet)
router.register(r'providerregionrate', api.ProviderRegionRateViewSet)
router.register(r'customerdefaultrate', api.CustomerDefaultRateViewSet)
router.register(r'providerdefaultrate', api.ProviderDefaultRateViewSet)


urlpatterns = (
    # urls for Django Rest Framework API
    path('api/v1/', include(router.urls)),
)

urlpatterns += (
    # urls for CustomerRcAllocation
    path('pyfb_rating/customerrcallocation/', views.CustomerRcAllocationListView.as_view(), name='pyfb_rating_customerrcallocation_list'),
    path('pyfb_rating/customerrcallocation/create/', views.CustomerRcAllocationCreateView.as_view(), name='pyfb_rating_customerrcallocation_create'),
    path('pyfb_rating/customerrcallocation/detail/<int:pk>/', views.CustomerRcAllocationDetailView.as_view(), name='pyfb_rating_customerrcallocation_detail'),
    path('pyfb_rating/customerrcallocation/update/<int:pk>/', views.CustomerRcAllocationUpdateView.as_view(), name='pyfb_rating_customerrcallocation_update'),
)

urlpatterns += (
    # urls for CallerNumList
    path('rate/callernumlist/', views.CallerNumListListView.as_view(), name='pyfb_rating_callernumlist_list'),
    path('rate/callernumlist/create/', views.CallerNumListCreateView.as_view(), name='pyfb_rating_callernumlist_create'),
    path('rate/callernumlist/detail/<slug:slug>/', views.CallerNumListDetailView.as_view(), name='pyfb_rating_callernumlist_detail'),
    path('rate/callernumlist/update/<slug:slug>/', views.CallerNumListUpdateView.as_view(), name='pyfb_rating_callernumlist_update'),
)

urlpatterns += (
    # urls for ProviderRatecard
    path('rate/providerratecard/', views.ProviderRatecardListView.as_view(), name='pyfb_rating_providerratecard_list'),
    path('rate/providerratecard/create/', views.ProviderRatecardCreateView.as_view(), name='pyfb_rating_providerratecard_create'),
    path('rate/providerratecard/detail/<slug:slug>/', views.ProviderRatecardDetailView.as_view(), name='pyfb_rating_providerratecard_detail'),
    path('rate/providerratecard/update/<slug:slug>/', views.ProviderRatecardUpdateView.as_view(), name='pyfb_rating_providerratecard_update'),
)

urlpatterns += (
    # urls for CustomerRatecard
    path('rate/customerratecard/', views.CustomerRatecardListView.as_view(), name='pyfb_rating_customerratecard_list'),
    path('rate/customerratecard/create/', views.CustomerRatecardCreateView.as_view(), name='pyfb_rating_customerratecard_create'),
    path('rate/customerratecard/detail/<slug:slug>/', views.CustomerRatecardDetailView.as_view(), name='pyfb_rating_customerratecard_detail'),
    path('rate/customerratecard/update/<slug:slug>/', views.CustomerRatecardUpdateView.as_view(), name='pyfb_rating_customerratecard_update'),
)

urlpatterns += (
    # urls for CustomerPrefixRate
    path('rate/customerprefixrate/', views.CustomerPrefixRateListView.as_view(), name='pyfb_rating_customerprefixrate_list'),
    path('rate/customerprefixrate/create/', views.CustomerPrefixRateCreateView.as_view(), name='pyfb_rating_customerprefixrate_create'),
    path('rate/customerprefixrate/detail/<int:pk>/', views.CustomerPrefixRateDetailView.as_view(), name='pyfb_rating_customerprefixrate_detail'),
    path('rate/customerprefixrate/update/<int:pk>/', views.CustomerPrefixRateUpdateView.as_view(), name='pyfb_rating_customerprefixrate_update'),
)

urlpatterns += (
    # urls for ProviderPrefixRate
    path('rate/providerprefixrate/', views.ProviderPrefixRateListView.as_view(), name='pyfb_rating_providerprefixrate_list'),
    path('rate/providerprefixrate/create/', views.ProviderPrefixRateCreateView.as_view(), name='pyfb_rating_providerprefixrate_create'),
    path('rate/providerprefixrate/detail/<int:pk>/', views.ProviderPrefixRateDetailView.as_view(), name='pyfb_rating_providerprefixrate_detail'),
    path('rate/providerprefixrate/update/<int:pk>/', views.ProviderPrefixRateUpdateView.as_view(), name='pyfb_rating_providerprefixrate_update'),
)

urlpatterns += (
    # urls for CustomerDestinationRate
    path('rate/customerdestinationrate/', views.CustomerDestinationRateListView.as_view(), name='pyfb_rating_customerdestinationrate_list'),
    path('rate/customerdestinationrate/create/', views.CustomerDestinationRateCreateView.as_view(), name='pyfb_rating_customerdestinationrate_create'),
    path('rate/customerdestinationrate/detail/<int:pk>/', views.CustomerDestinationRateDetailView.as_view(), name='pyfb_rating_customerdestinationrate_detail'),
    path('rate/customerdestinationrate/update/<int:pk>/', views.CustomerDestinationRateUpdateView.as_view(), name='pyfb_rating_customerdestinationrate_update'),
)

urlpatterns += (
    # urls for ProviderDestinationRate
    path('rate/providerdestinationrate/', views.ProviderDestinationRateListView.as_view(), name='pyfb_rating_providerdestinationrate_list'),
    path('rate/providerdestinationrate/create/', views.ProviderDestinationRateCreateView.as_view(), name='pyfb_rating_providerdestinationrate_create'),
    path('rate/providerdestinationrate/detail/<int:pk>/', views.ProviderDestinationRateDetailView.as_view(), name='pyfb_rating_providerdestinationrate_detail'),
    path('rate/providerdestinationrate/update/<int:pk>/', views.ProviderDestinationRateUpdateView.as_view(), name='pyfb_rating_providerdestinationrate_update'),
)

urlpatterns += (
    # urls for CustomerCountryTypeRate
    path('rate/customercountrytyperate/', views.CustomerCountryTypeRateListView.as_view(), name='pyfb_rating_customercountrytyperate_list'),
    path('rate/customercountrytyperate/create/', views.CustomerCountryTypeRateCreateView.as_view(), name='pyfb_rating_customercountrytyperate_create'),
    path('rate/customercountrytyperate/detail/<int:pk>/', views.CustomerCountryTypeRateDetailView.as_view(), name='pyfb_rating_customercountrytyperate_detail'),
    path('rate/customercountrytyperate/update/<int:pk>/', views.CustomerCountryTypeRateUpdateView.as_view(), name='pyfb_rating_customercountrytyperate_update'),
)

urlpatterns += (
    # urls for ProviderCountryTypeRate
    path('rate/providercountrytyperate/', views.ProviderCountryTypeRateListView.as_view(), name='pyfb_rating_providercountrytyperate_list'),
    path('rate/providercountrytyperate/create/', views.ProviderCountryTypeRateCreateView.as_view(), name='pyfb_rating_providercountrytyperate_create'),
    path('rate/providercountrytyperate/detail/<int:pk>/', views.ProviderCountryTypeRateDetailView.as_view(), name='pyfb_rating_providercountrytyperate_detail'),
    path('rate/providercountrytyperate/update/<int:pk>/', views.ProviderCountryTypeRateUpdateView.as_view(), name='pyfb_rating_providercountrytyperate_update'),
)

urlpatterns += (
    # urls for CustomerCountryRate
    path('rate/customercountryrate/', views.CustomerCountryRateListView.as_view(), name='pyfb_rating_customercountryrate_list'),
    path('rate/customercountryrate/create/', views.CustomerCountryRateCreateView.as_view(), name='pyfb_rating_customercountryrate_create'),
    path('rate/customercountryrate/detail/<int:pk>/', views.CustomerCountryRateDetailView.as_view(), name='pyfb_rating_customercountryrate_detail'),
    path('rate/customercountryrate/update/<int:pk>/', views.CustomerCountryRateUpdateView.as_view(), name='pyfb_rating_customercountryrate_update'),
)

urlpatterns += (
    # urls for ProviderCountryRate
    path('rate/providercountryrate/', views.ProviderCountryRateListView.as_view(), name='pyfb_rating_providercountryrate_list'),
    path('rate/providercountryrate/create/', views.ProviderCountryRateCreateView.as_view(), name='pyfb_rating_providercountryrate_create'),
    path('rate/providercountryrate/detail/<int:pk>/', views.ProviderCountryRateDetailView.as_view(), name='pyfb_rating_providercountryrate_detail'),
    path('rate/providercountryrate/update/<int:pk>/', views.ProviderCountryRateUpdateView.as_view(), name='pyfb_rating_providercountryrate_update'),
)

urlpatterns += (
    # urls for CustomerRegionTypeRate
    path('rate/customerregiontyperate/', views.CustomerRegionTypeRateListView.as_view(), name='pyfb_rating_customerregiontyperate_list'),
    path('rate/customerregiontyperate/create/', views.CustomerRegionTypeRateCreateView.as_view(), name='pyfb_rating_customerregiontyperate_create'),
    path('rate/customerregiontyperate/detail/<int:pk>/', views.CustomerRegionTypeRateDetailView.as_view(), name='pyfb_rating_customerregiontyperate_detail'),
    path('rate/customerregiontyperate/update/<int:pk>/', views.CustomerRegionTypeRateUpdateView.as_view(), name='pyfb_rating_customerregiontyperate_update'),
)

urlpatterns += (
    # urls for ProviderRegionTypeRate

pyfb_rating/forms.py
from django import forms
from .models import CustomerRcAllocation, CallerNumList, ProviderRatecard, CustomerRatecard, CustomerPrefixRate, ProviderPrefixRate, CustomerDestinationRate, ProviderDestinationRate, CustomerCountryTypeRate, ProviderCountryTypeRate, CustomerCountryRate, ProviderCountryRate, CustomerRegionTypeRate, ProviderRegionTypeRate, CustomerRegionRate, ProviderRegionRate, CustomerDefaultRate, ProviderDefaultRate


class CustomerRcAllocationForm(forms.ModelForm):
    class Meta:
        model = CustomerRcAllocation
        fields = ['tech_prefix', 'priority', 'discount', 'allow_negative_margin', 'description', 'customer', 'ratecard']


class CallerNumListForm(forms.ModelForm):
    class Meta:
        model = CallerNumList
        fields = ['name', 'callerid_filter', 'destination']


class ProviderRatecardForm(forms.ModelForm):
    class Meta:
        model = ProviderRatecard
        fields = ['name', 'rc_type', 'provider_prefix', 'estimated_quality', 'date_start', 'date_end', 'status', 'status_changed']


class CustomerRatecardForm(forms.ModelForm):
    class Meta:
        model = CustomerRatecard
        fields = ['rc_type', 'name', 'status', 'status_changed']


class CustomerPrefixRateForm(forms.ModelForm):
    class Meta:
        model = CustomerPrefixRate
        fields = ['prefix', 'destnum_length', 'c_ratecard', 'r_rate', 'status']


class ProviderPrefixRateForm(forms.ModelForm):
    class Meta:
        model = ProviderPrefixRate
        fields = ['prefix', 'destnum_length', 'p_ratecard', 'r_rate', 'status']


class CustomerDestinationRateForm(forms.ModelForm):
    class Meta:
        model = CustomerDestinationRate
        fields = ['c_ratecard', 'destination', 'r_rate', 'status']


class ProviderDestinationRateForm(forms.ModelForm):
    class Meta:
        model = ProviderDestinationRate
        fields = ['p_ratecard', 'destination', 'r_rate', 'status']


class CustomerCountryTypeRateForm(forms.ModelForm):
    class Meta:
        model = CustomerCountryTypeRate
        fields = ['c_ratecard', 'country', 'type', 'r_rate', 'status']


class ProviderCountryTypeRateForm(forms.ModelForm):
    class Meta:
        model = ProviderCountryTypeRate
        fields = ['p_ratecard', 'country', 'type', 'r_rate', 'status']


class CustomerCountryRateForm(forms.ModelForm):
    class Meta:
        model = CustomerCountryRate
        fields = ['c_ratecard', 'country', 'r_rate', 'status']


class ProviderCountryRateForm(forms.ModelForm):
    class Meta:
        model = ProviderCountryRate
        fields = ['p_ratecard', 'country', 'r_rate', 'status']


class CustomerRegionTypeRateForm(forms.ModelForm):
    class Meta:
        model = CustomerRegionTypeRate
        fields = ['c_ratecard', 'region', 'type', 'r_rate', 'status']


class ProviderRegionTypeRateForm(forms.ModelForm):
    class Meta:
        model = ProviderRegionTypeRate
        fields = ['p_ratecard', 'region', 'type', 'r_rate', 'status']


class CustomerRegionRateForm(forms.ModelForm):
    class Meta:
        model = CustomerRegionRate
        fields = ['c_ratecard', 'region', 'r_rate', 'status']


class ProviderRegionRateForm(forms.ModelForm):
    class Meta:
        model = ProviderRegionRate
        fields = ['p_ratecard', 'region', 'r_rate', 'status']


class CustomerDefaultRateForm(forms.ModelForm):
    class Meta:
        model = CustomerDefaultRate
        fields = ['c_ratecard', 'r_rate', 'status']


class ProviderDefaultRateForm(forms.ModelForm):
    class Meta:
        model = ProviderDefaultRate
        fields = ['p_ratecard', 'r_rate', 'status']

pyfb_rating/templates/pyfb_rating/callernumlist_form.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-rating:pyfb_rating_callernumlist_list' %}">CallerNumList Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

pyfb_rating/templates/pyfb_rating/callernumlist_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-rating:pyfb_rating_callernumlist_list' %}">CallerNumList Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>name</td>
    <td>slug</td>
    <td>callerid_filter</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.name }}</td>
    <td>{{ object.slug }}</td>
    <td>{{ object.callerid_filter }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'pyfb-rating:pyfb_rating_callernumlist_create' %}">Create new CallerNumList</a>
{% endblock %}

pyfb_rating/templates/pyfb_rating/customercountryrate_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-rating:pyfb_rating_customercountryrate_list' %}">CustomerCountryRate Listing</a></p>
<table class="table">
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit CustomerCountryRate</a>

{% endblock %}

pyfb_rating/templates/pyfb_rating/customerdefaultrate_form.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-rating:pyfb_rating_customerdefaultrate_list' %}">CustomerDefaultRate Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

pyfb_rating/templates/pyfb_rating/customerrcallocation_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-rating:pyfb_rating_customerrcallocation_list' %}">CustomerRcAllocation Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

pyfb_rating/templates/pyfb_rating/customerregionrate_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-rating:pyfb_rating_customerregionrate_list' %}">CustomerRegionRate Listing</a></p>
<table class="table">
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit CustomerRegionRate</a>

{% endblock %}

pyfb_rating/templates/pyfb_rating/customerregiontyperate_form.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-rating:pyfb_rating_customerregiontyperate_list' %}">CustomerRegionTypeRate Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

pyfb_rating/templates/pyfb_rating/customerregiontyperate_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-rating:pyfb_rating_customerregiontyperate_list' %}">CustomerRegionTypeRate Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'pyfb-rating:pyfb_rating_customerregiontyperate_create' %}">Create new CustomerRegionTypeRate</a>
{% endblock %}

pyfb_rating/templates/pyfb_rating/providercountryrate_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-rating:pyfb_rating_providercountryrate_list' %}">ProviderCountryRate Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'pyfb-rating:pyfb_rating_providercountryrate_create' %}">Create new ProviderCountryRate</a>
{% endblock %}

pyfb_rating/templates/pyfb_rating/providercountrytyperate_form.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-rating:pyfb_rating_providercountrytyperate_list' %}">ProviderCountryTypeRate Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

pyfb_rating/templates/pyfb_rating/providercountrytyperate_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-rating:pyfb_rating_providercountrytyperate_list' %}">ProviderCountryTypeRate Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'pyfb-rating:pyfb_rating_providercountrytyperate_create' %}">Create new ProviderCountryTypeRate</a>
{% endblock %}

pyfb_rating/templates/pyfb_rating/providerprefixrate_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-rating:pyfb_rating_providerprefixrate_list' %}">ProviderPrefixRate Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>prefix</td>
    <td>destnum_length</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.prefix }}</td>
    <td>{{ object.destnum_length }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'pyfb-rating:pyfb_rating_providerprefixrate_create' %}">Create new ProviderPrefixRate</a>
{% endblock %}

pyfb_rating/templates/pyfb_rating/providerregionrate_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-rating:pyfb_rating_providerregionrate_list' %}">ProviderRegionRate Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'pyfb-rating:pyfb_rating_providerregionrate_create' %}">Create new ProviderRegionRate</a>
{% endblock %}

pyfb_rating/templates/pyfb_rating/providerregiontyperate_form.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-rating:pyfb_rating_providerregiontyperate_list' %}">ProviderRegionTypeRate Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}